matrix:
  include:
    - os: linux
      language: python
      python: 3.6
      sudo: required
    - os: osx
      language: python
      python: 3.6

before_install:
#-------------------------------------------------------------------------------
#Specific to Linux
#-------------------------------------------------------------------------------
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get --version             ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y $(grep -v -E '(^#|^$)' requirements.apt) ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt list --installed          ; fi

#-------------------------------------------------------------------------------
#Specific to OSX
#-------------------------------------------------------------------------------
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew --version                  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall $(grep -v -E '(^#|^$)' requirements.brw) ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list                       ; fi

#-------------------------------------------------------------------------------
#Checking environment details (OS-agnostic)
#-------------------------------------------------------------------------------

- echo $TRAVIS_OS_NAME
- which python
- python --version
- which pip
- pip --version

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install `grep 'pip==' requirements.pip` ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install `grep 'pip==' requirements.pip` ; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell "python -m pip install ((gc requirements.pip) -match 'pip==')" ; fi
- which pip
- pip --version
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install -r requirements.pip  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install -r requirements.pip  ; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python -m pip install -r requirements.pip ; fi

#language: python
#python:
#  - "3.6"
#install: 
#  - pip install -r requirements.txt
script:
  - cd ./src
  - pytest
after_success:
 - python orchestrate.py
