matrix:
  include:
    - os: linux
      language: python
      python:
        - "3.6.3"
      sudo: required
    - os: osx
      language: generic
      env: PYTHONPATH=/usr/local/lib/python3.6

#before_install: 
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
#language: python
#python:
  #- "3.6"
install: 
  - pip3 install -r requirements.txt
script:
  - cd ./src
  - python3 orchestrate.py
#after_success:
# - python3 orchestrate.py
