matrix:
  include:
    - os: linux
      language: python3.6.3
      sudo: required
    - os: osx
      language: python3.6.3

#language: python
#python:
  #- "3.6"
install: 
  - pip install -r requirements.txt
script:
  - cd ./src
  - pytest
after_success:
 - python orchestrate.py
