matrix:
  include:
    - os: linux
      language: python
      python: 
        - "3.6.3"
      sudo: required
    - os: osx
      language: generic
      env: PYTHON=3.6

if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew upgrade python;
  fi

#language: python
#python:
  #- "3.6"
install: 
  - pip install -r requirements.txt
script:
  - cd ./src
  - pytest
after_success:
 - python orchestrate.py
